---

- name: restart postfix
  service:
      name: postfix
      state: restarted

- name: reload postfix
  service:
      name: postfix
      state: reload

- name: update aliases db 
  command: postalias /etc/postfix/aliases

- name: update virtual db 
  command: postmap /etc/postfix/virtual
