- name: make archlinux user
  user: name=archlinux shell=/bin/false home={{ path }} createhome=no

- name: fix home permissions
  file: state=directory owner=archlinux group=archlinux path="{{ path }}"

- name: clone archlinux.no repo
  git: repo=https://github.com/foxboron/archlinux.no.git dest="{{ path }}"
  become: true
  become_user: archlinux

- name: generate hugo site
  command: hugo 
  become: true 
  become_user: archlinux
  args:
    chdir: "{{path}}"

- name: install letsencrypt cert
  command: certbot certonly --rsa-key-size 4096 --renew-by-default --webroot -w /var/www/challenges -d {{ domain }} creates=/etc/letsencrypt/live/{{domain}}

- name: make nginx log dir
  file: path=/var/log/nginx/{{ domain }} state=directory owner=www-data group=adm mode=755

- name: set up nginx
  template: src=../templates/nginx.d.conf.j2 dest=/etc/nginx/nginx.d/archlinux.no.conf owner=root group=root mode=644
  notify:
    - restart nginx
