---

- name: make blog user
  user: name=blog shell=/bin/false home={{ path }} createhome=no

- name: fix home permissions
  file: state=directory owner=blog group=blog path="{{ path }}"

- name: copy base blog
  copy: src=blog/ dest={{ path }} owner=blog group=blog mode=0644

- name: install letsencrypt cert
  command: certbot certonly --rsa-key-size 4096 --renew-by-default --webroot -w /var/www/challenges -d {{ domain }} creates=/etc/letsencrypt/live/{{domain}}


- name: make nginx log dir
  file: path=/var/log/nginx/{{ domain }} state=directory owner=www-data group=adm mode=755

- name: set up nginx
  template: src=../templates/nginx.d.conf.j2 dest=/etc/nginx/nginx.d/blog.conf owner=root group=root mode=644
  notify:
    - restart nginx


