---

- name: install opendkim
  pacman: name=opendkim state=present

- name: install opendkim.conf
  template: src=opendkim.conf.j2 dest=/etc/opendkim/opendkim.conf owner=root group=root mode=0644
  notify:
    - restart opendkim

- file: path="/var/spool/opendkim/" state=directory owner=opendkim group=opendkim mode=0750

- name: install domains config
  template: src=domains.j2 dest=/etc/opendkim/domains owner=root group=root mode=0644
  notify:
    - restart opendkim

- file: path="/etc/opendkim/private" state=directory owner=root group=root mode=0700

- name: generate DKIM key for {{dkim_selector}}
  command: opendkim-genkey -r -s {{dkim_selector}} -d linderud.pw --bits=4096
  args:
    creates: /etc/opendkim/private/{{dkim_selector}}.private
    chdir: /etc/opendkim/private

# see README.md for instruction on how to add the key to DNS. This will fail unless the key in DNS is correct!
- name: verify key in dns
  command: opendkim-testkey  -d linderud.pw -s {{dkim_selector}} -k /etc/opendkim/private/{{dkim_selector}}.private -vvv
  tags:
    - dkimverify

- name: start and enable opendkim
  service: name=opendkim enabled=yes state=started
