---
- name: install cgit fcgiwrap
  package: name=cgit,fcgiwrap state=present

- name: append git group to www-data 
  user:
    name: "{{ http_user_group[0] }}"
    groups: git 
    append: yes

- name: install cgitrc
  template: src=cgitrc dest=/etc/cgitrc owner=root group=root mode=0644

- name: make nginx log dir
  file: path=/var/log/nginx/{{ domain }} state=directory owner=www-data group=adm mode=755

- include: ../tasks/ssl.yml

- name: install nginx file
  template: src=../templates/nginx.d.conf.j2 dest=/etc/nginx/nginx.d/cgit.conf owner=root group=root mode=0644
  notify: 
    - add ssl
    - restart nginx
    - restart fcgiwrap
