---

- name: install certbot
  package: name=certbot state=present

- name: check for letsencrypt account
  stat: path=/etc/letsencrypt/account
  register: account

- name: create challenge directory
  file: state=directory path={{ letsencrypt_validation_dir }} owner=root group=root mode=0755

- name: register account
  command: certbot register -m morten@linderud.pw --agree-tos
  when: account == False

- name: install letsencrypt service
  copy: src="letsencrypt.service" dest="/etc/systemd/system/letsencrypt.service" owner=root group=root mode=0644

- name: install letsencrypt timer 
  copy: src="letsencrypt.timer" dest="/etc/systemd/system/letsencrypt.timer" owner=root group=root mode=0644
  notify:
    - daemon reload

- name: create nginx service override directory
  file: state=directory path=/lib/systemd/system/nginx.service.d owner=root group=root mode=0755

- name: install nginx service override
  copy: src="nginx-override.conf" dest="/lib/systemd/system/nginx.service.d/10-letsencrypt.conf" owner=root group=root mode=0644
  notify:
    - daemon reload

- name: create unique DH group
  command: openssl dhparam -out /etc/ssl/dhparams.pem 2048 creates=/etc/ssl/dhparams.pem

- name: install nginx snippets
  template: src={{ item }}  dest=/etc/nginx/snippets owner=root  group=root mode=0644
  with_items:
    - sslsettings.conf
  notify:
    - reload nginx

- name: install nginx vhost config
  template: src="nginx-hostname-vhost.conf.j2" dest="/etc/nginx/nginx.d/nginx-hostname-vhost.conf" owner=root group=root mode=0755
  notify:
    - restart nginx

- name: restart nginx
  service: name=nginx state=reloaded

- name: fetch domains
  command: certbot certonly --rsa-key-size 4096 --renew-by-default --webroot -w /var/www/challenges -d {{ item }} creates=/etc/letsencrypt/live/{{item}}
  with_items: "{{domains}}"
