---

- name: setup linderud.dev
  hosts: linderud
  roles:
      - { role: common, tags: ['common']}

      - { role: nginx,
          tags: ['nginx']}

      - { role: letsencrypt,
          domains: [
             "linderud.pw",
             "smtp.linderud.pw",
             "imap.linderud.pw",
             "linderud.dev",
             "bloat.dev",
             "velox.pw",
          ],
          tags: ['letsencrypt']}

      - { role: hugo,
          ssl: true,
          hugo_user: blog,
          hugo_repo: "https://github.com/foxboron/blog.git",
          domain: "linderud.dev", 
          path: "/srv/http/blog", 
          tags: ['hugo', 'blog']}

      - { role: wkd , tags: ['wkd'] }

