---

- name: setup velox
  hosts: velox
  vars:
    letsencrypt_certs: "/etc/nginx/certs"
    http_user_group: ["www-data", "www-data"]
  roles:
      - { role: common, tags: ['common']}
      - { role: nginx,
          letsencrypt_validation_dir: "/srv/http/letsencrypt",
          letsencrypt_config_dir: "/etc/nginx/letsencrypt",
          domains: [".velox.pw",".vulpes.pw"],
          tags: ['cgit', 'blog', 'nginx']}
      - { role: blog,
          ssl: true,
          domain: "velox.pw", 
          path: "/srv/http/blog", 
          tags: ['blog']}
      - { role: irc, 
          domain: "irc.velox.pw", 
          tags: ['irc']}
      - { role: gitolite,
          path: "/srv/git",
          admin_keys: ["fox.pub"],
          tags: ['gitolite','git']}
      - { role: cgit,
          ssl: true,
          path: "/srv/git",
          domain: "git.velox.pw",
          tags: ['cgit', 'git']}
      - { role: pics,
          ssl: true,
          path: "/srv/pics",
          ssh_key: "fox.pub",
          domain: "pics.velox.pw",
          tags: ['pics']}

