---

- name: setup velox
  hosts: velox
  vars:
      git_path: "/srv/git"
  roles:
      - { role: common, tags: ['common']}

      - { role: nginx,
          tags: ['nginx']}

      - { role: letsencrypt,
          tags: ['letsencrypt']}

      - { role: hugo,
          ssl: true,
          hugo_user: blog,
          hugo_repo: "https://github.com/foxboron/blog.git",
          domain: "linderud.dev", 
          path: "/srv/http/blog", 
          tags: ['hugo', 'blog']}

      - { role: hugo,
          ssl: true,
          hugo_user: archlinux,
          hugo_repo: "https://github.com/foxboron/archlinux.no.git",
          domain: "archlinux.no",
          path: "/srv/http/archlinux.no",
          tags: ['hugo', 'archlinux.no']}

      # - { role: irc, 
      #     domain: "irc.velox.pw", 
      #     tags: ['irc']}

      # - { role: gitolite,
      #     admin_keys: ["fox.pub"],
      #     tags: ['gitolite','git']}

      - { role: cgit,
          ssl: true,
          path: "/srv/http/cgit",
          domain: "git.linderud.dev",
          tags: ['cgit', 'git']}

      # - { role: pics,
      #     ssl: true,
      #     path: "/srv/pics",
      #     ssh_key: "fox.pub",
      #     domain: "pics.velox.pw",
      #     tags: ['pics']}

      # - { role: backup, 
      #     backup_keys: ["fox.pub", "theia.pub"],
      #     tags: ['backup']}
      
      # - { role: wireguard,
      #     tags: ['wireguard']}

