---

- name: setup velox
  hosts: velox
  vars:
      git_path: "/srv/git"
  roles:
      - { role: common, tags: ['common']}

      - { role: nginx,
          tags: ['nginx']}

      - { role: letsencrypt,
          tags: ['letsencrypt']}

      - { role: blog,
          ssl: true,
          domain: "velox.pw", 
          path: "/srv/http/blog", 
          tags: ['blog']}

      - { role: irc, 
          domain: "irc.velox.pw", 
          tags: ['irc']}

      - { role: gitolite,
          admin_keys: ["fox.pub"],
          tags: ['gitolite','git']}

      - { role: cgit,
          ssl: true,
          path: "/srv/http/cgit",
          domain: "git.velox.pw",
          tags: ['cgit', 'git']}

      - { role: pics,
          ssl: true,
          path: "/srv/pics",
          ssh_key: "fox.pub",
          domain: "pics.velox.pw",
          tags: ['pics']}

      - { role: backup, 
          backup_keys: ["fox.pub", "theia.pub"],
          tags: ['backup']}

      - { role: repo,
          ssl: true,
          path: "/srv/repo",
          domain: "repos.buelinux.no",
          keys: ["fox.pub", "theia.pub"],
          tags: ['repo']}

      - { role: buildbot,
          ssl: true,
          path: "/srv/buildbot",
          domain: "build.velox.pw",
          tags: ['buildbot']}

      - { role: uwsgi,
          tags: ['uwsgi']}
      
      - { role: elasticsearch-flask,
          domain: "es.velox.pw",
          ssl: true,
          es_dir: "/srv/es",
          tags: ['es']}
