---

- name: install nginx
  apt: name=nginx state=present
  #apt: name=nginx,php5-fpm state=present

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify:
      - restart nginx

- name: snippets directory
  file: state=directory path=/etc/nginx/snippets owner=root group=root mode=0755

- name: create nginx.d directory
  file: state=directory path=/etc/nginx/nginx.d owner=root group=root mode=0755

- name: create default nginx log directory
  file: state=directory path=/var/log/nginx/default owner=www-data group=adm mode=0750

# - name: install php5-fpm config
#   template: src=php-fpm.conf.j2 dest=/etc/php5/fpm owner=root group=root mode=0644
#   notify:
#       - restart php5-fpm

- name: enable nginx
  service: name=nginx enabled=yes
  notify:
    - reload nginx
